/*
 * generated by Xtext 2.17.0
 */
package zd.zero.abdt.eclipse


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AnyaBasicStandaloneSetup extends AnyaBasicStandaloneSetupGenerated {

	def static void doSetup() {
		new AnyaBasicStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
