/*
 * generated by Xtext 2.17.0
 */
package zd.zero.abdt.eclipse


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class AnyaBasicRuntimeModule extends AbstractAnyaBasicRuntimeModule {
}
