/**
 * generated by Xtext 2.17.0
 */
package zd.zero.abdt.eclipse.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import zd.zero.abdt.eclipse.ui.AbstractAnyaBasicUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AnyaBasicUiModule extends AbstractAnyaBasicUiModule {
  public AnyaBasicUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
