/**
 * generated by Xtext 2.17.0
 */
package zd.zero.abdt.eclipse;

import zd.zero.abdt.eclipse.AbstractAnyaBasicRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AnyaBasicRuntimeModule extends AbstractAnyaBasicRuntimeModule {
}
