/**
 * generated by Xtext 2.17.0
 */
package zd.zero.abdt.eclipse;

import zd.zero.abdt.eclipse.AnyaBasicStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AnyaBasicStandaloneSetup extends AnyaBasicStandaloneSetupGenerated {
  public static void doSetup() {
    new AnyaBasicStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
