/**
 * generated by Xtext 2.17.0
 */
package zd.zero.abdt.eclipse.ui.contentassist;

import zd.zero.abdt.eclipse.ui.contentassist.AbstractAnyaBasicProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class AnyaBasicProposalProvider extends AbstractAnyaBasicProposalProvider {
}
