/**
 * generated by Xtext 2.17.0
 */
package zd.zero.abdt.eclipse.validation;

import zd.zero.abdt.eclipse.validation.AbstractAnyaBasicValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AnyaBasicValidator extends AbstractAnyaBasicValidator {
}
