/*
 * generated by Xtext 2.17.0
 */
package zd.zero.abdt.eclipse.ui;

import abdt.ui.internal.AbdtActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AnyaBasicExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(AbdtActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		AbdtActivator activator = AbdtActivator.getInstance();
		return activator != null ? activator.getInjector(AbdtActivator.ZD_ZERO_ABDT_ECLIPSE_ANYABASIC) : null;
	}

}
