/**
 * generated by Xtext 2.17.0
 */
package zd.zero.abdt.eclipse.ide;

import zd.zero.abdt.eclipse.ide.AbstractAnyaBasicIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class AnyaBasicIdeModule extends AbstractAnyaBasicIdeModule {
}
