/*
 * generated by Xtext 2.17.0
 */
package zd.zero.abdt.eclipse.ui.tests;

import abdt.ui.internal.AbdtActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class AnyaBasicUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AbdtActivator.getInstance().getInjector("zd.zero.abdt.eclipse.AnyaBasic");
	}

}
