/**
 * generated by Xtext 2.17.0
 */
package zd.zero.abdt.eclipse.scoping;

import zd.zero.abdt.eclipse.scoping.AbstractAnyaBasicScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class AnyaBasicScopeProvider extends AbstractAnyaBasicScopeProvider {
}
