/*
 * generated by Xtext 2.17.0
 */
package zd.zero.abdt.eclipse.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class AnyaBasicScopeProvider extends AbstractAnyaBasicScopeProvider {

}
