/*
 * generated by Xtext 2.17.0
 */
package zd.zero.abdt.eclipse.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAnyaBasicScopeProvider extends DelegatingScopeProvider {
}
