/*
 * generated by Xtext 2.17.0
 */
package zd.zero.abdt.eclipse.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import zd.zero.abdt.eclipse.parser.antlr.internal.InternalAnyaBasicParser;
import zd.zero.abdt.eclipse.services.AnyaBasicGrammarAccess;

public class AnyaBasicParser extends AbstractAntlrParser {

	@Inject
	private AnyaBasicGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAnyaBasicParser createParser(XtextTokenStream stream) {
		return new InternalAnyaBasicParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public AnyaBasicGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AnyaBasicGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
