/*
 * generated by Xtext 2.17.0
 */
package zd.zero.abdt.eclipse.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AnyaBasicAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("zd/zero/abdt/eclipse/parser/antlr/internal/InternalAnyaBasic.tokens");
	}
}
